<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UserID  EngineerTest1</name>
   <tag></tag>
   <elementGuidId>9b4df206-ccd0-4f91-a7ac-3a89fa7af05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='barUserID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#barUserID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>063af396-fa06-4815-9a7a-fc3f83669195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-toolbar-text x-box-item x-toolbar-item x-toolbar-text-default</value>
      <webElementGuid>14dfa0e8-48be-4161-a4c1-a289ec2bcb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>barUserID</value>
      <webElementGuid>ecd3e1db-57d6-4fe6-b76b-8ca7d014bd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UserID : EngineerTest1</value>
      <webElementGuid>72d31449-cbd2-4839-b93b-73d034f4a8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;barUserID&quot;)</value>
      <webElementGuid>5c9982b4-a9f2-4060-b771-5095a83ca4aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='barUserID']</value>
      <webElementGuid>c8902445-dd67-4e30-beb1-5709f5b44ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StatusBar1-targetEl']/div[4]</value>
      <webElementGuid>c1f8bec8-dbd6-4891-b0a9-e8317f0ae687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]</value>
      <webElementGuid>9a883bec-78da-4a9b-b58b-f2cd049b72eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'barUserID' and (text() = 'UserID : EngineerTest1' or . = 'UserID : EngineerTest1')]</value>
      <webElementGuid>049eb323-9443-4bbe-a1ed-bdaf6b4233ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
