<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The Username and Password fields are both required</name>
   <tag></tag>
   <elementGuidId>ea8a9320-790c-4da2-864f-1b6c622834bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='messagebox-1001-msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#messagebox-1001-msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54b74752-4f74-4aae-989c-1d76d4609cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-window-text x-box-item x-component-default</value>
      <webElementGuid>93488589-7188-4217-ad03-a1370f32836e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messagebox-1001-msg</value>
      <webElementGuid>2898bb38-70bb-4501-84a3-a30af512de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Username and Password fields are both required</value>
      <webElementGuid>6e73743d-110e-4160-8960-f75ccec8e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messagebox-1001-msg&quot;)</value>
      <webElementGuid>2e847e41-373c-46f7-9863-261b140d6436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='messagebox-1001-msg']</value>
      <webElementGuid>5886d5f5-7e77-486c-b910-d8d3e953b8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-1003-targetEl']/div</value>
      <webElementGuid>9eca1f7e-7a3f-4236-b95d-54811703c089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>3dff1705-ecf8-420a-8db1-00c0390f1885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'messagebox-1001-msg' and (text() = 'The Username and Password fields are both required' or . = 'The Username and Password fields are both required')]</value>
      <webElementGuid>b6a51de8-3a2a-48ab-9b01-0054dc0d5201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
